pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "WOrkspace is:: ${WORKSPACE}"
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too..ddd"
                    ls -lah
                '''
                sh '.\temp.sh'


            }
        }
    }
}
