pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "WOrkspace is:: ${WORKSPACE}"
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too..ddd"
                    ls -lah
                '''
                       script1 {
                        tempSH = "${WORKSPACE}/temp.sh"
                       sh "chmod +x -R ${env.WORKSPACE}"
                       echo "tempSH ${tempSH}"
                       sh "${tempSH}"
                      }

            }
        }
    }
}
